runtime: nodejs16

env_variables:
  CLOUDINARY_API_KEY: '$CLOUDINARY_API_KEY'
  CLOUDINARY_API_SECRET: '$CLOUDINARY_API_SECRET'
  CLOUDINARY_CLOUD_NAME: '$CLOUDINARY_CLOUD_NAME'
  DATABASE_URI: '$DATABASE_URI'
  JWT_SECRET: '$JWT_SECRET'
  REDDIT_APP_ID: '$REDDIT_APP_ID'
  REDDIT_SECRET: '$REDDIT_SECRET'
  TWILIO_AUTH_TOKEN: '$TWILIO_AUTH_TOKEN'
  TWITTER_API_KEY: '$TWITTER_API_KEY'
  TWITTER_API_SECRET: '$TWITTER_API_SECRET'
  TWITTER_BEARER_TOKEN: '$TWITTER_BEARER_TOKEN'
  TWITTER_CLIENT_ID: '$TWITTER_CLIENT_ID'
  TWITTER_ACCESS_KEY: '$TWITTER_ACCESS_KEY-YddjSjdqtWYRNC89SKsx1H6t9nvBZv'
  TWITTER_ACCESS_SECRET: '$TWITTER_ACCESS_SECRET'
  TWITTER_CLIENT_SECRET: '$TWITTER_CLIENT_SECRET'
  YOUTUBE_API_KEY: '$YOUTUBE_API_KEY'
  YOUTUBE_CLIENT_ID: '$YOUTUBE_CLIENT_ID'
  YOUTUBE_CLIENT_SECRET: '$YOUTUBE_CLIENT_SECRET'
