runtime: nodejs16

env_variables:
  CLOUDINARY_API_KEY: '$CLOUDINARY_API_KEY'
  CLOUDINARY_API_SECRET: '$CLOUDINARY_API_SECRET'
  CLOUDINARY_CLOUD_NAME: '$CLOUDINARY_CLOUD_NAME'
  DATABASE_URI: '$DATABASE_URI'
  JWT_SECRET: '$JWT_SECRET'
  REDDIT_APP_ID: '$REDDIT_APP_ID'
  REDDIT_SECRET: '$REDDIT_SECRET'
  TWILIO_AUTH_TOKEN: '$TWILIO_AUTH_TOKEN'
