name: Deploy Backend to Google App Engine

on:
  push:
    branches:
      - chris/deploymentTest

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./backend/
        run: npm ci

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Deploy to App Engine
        id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          working_directory: './backend/'
